<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Label extends Model
{
	public function save( array $options = [] ) {

		cache()->forget('labels');

		return parent::save( $options );
	}

	public function delete() {

		cache()->forget('labels');

		return parent::delete(); // TODO: Change the autogenerated stub
	}


}
